package com.linghua.hdds.meta;


import java.util.Map;

public class WebPage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.url
     *
     * @mbggenerated
     */
    private String url;
    
    
    private Map<String, String> meta;
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.fetch_time
     *
     * @mbggenerated
     */
    private String fetchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.prev_fetch_time
     *
     * @mbggenerated
     */
    private Long prevFetchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.fetch_interval
     *
     * @mbggenerated
     */
    private Integer fetchInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.retries_since_fetch
     *
     * @mbggenerated
     */
    private Integer retriesSinceFetch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.modified_time
     *
     * @mbggenerated
     */
    private Long modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.prev_modified_time
     *
     * @mbggenerated
     */
    private Long prevModifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.content_type
     *
     * @mbggenerated
     */
    private String contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.text
     *
     * @mbggenerated
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.score
     *
     * @mbggenerated
     */
    private Float score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.repr_url
     *
     * @mbggenerated
     */
    private String reprUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.batch_id
     *
     * @mbggenerated
     */
    private String batchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.segment_id
     *
     * @mbggenerated
     */
    private String segmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.firstFetchTime
     *
     * @mbggenerated
     */
    private String firstfetchtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.quote
     *
     * @mbggenerated
     */
    private String quote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.pubDate
     *
     * @mbggenerated
     */
    private String pubdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.tag
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_webpage_backup.catagory
     *
     * @mbggenerated
     */
    private String catagory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.url
     *
     * @return the value of cms_webpage_backup.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.url
     *
     * @param url the value for cms_webpage_backup.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.status
     *
     * @return the value of cms_webpage_backup.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.status
     *
     * @param status the value for cms_webpage_backup.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.fetch_time
     *
     * @return the value of cms_webpage_backup.fetch_time
     *
     * @mbggenerated
     */
    public String getFetchTime() {
        return fetchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.fetch_time
     *
     * @param fetchTime the value for cms_webpage_backup.fetch_time
     *
     * @mbggenerated
     */
    public void setFetchTime(String fetchTime) {
        this.fetchTime = fetchTime == null ? null : fetchTime.trim();
    }

    
    
    
    
    public Map<String, String> getMeta() {
		return meta;
	}

	public void setMeta(Map<String, String> meta) {
		this.meta = meta;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.prev_fetch_time
     *
     * @return the value of cms_webpage_backup.prev_fetch_time
     *
     * @mbggenerated
     */
    public Long getPrevFetchTime() {
        return prevFetchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.prev_fetch_time
     *
     * @param prevFetchTime the value for cms_webpage_backup.prev_fetch_time
     *
     * @mbggenerated
     */
    public void setPrevFetchTime(Long prevFetchTime) {
        this.prevFetchTime = prevFetchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.fetch_interval
     *
     * @return the value of cms_webpage_backup.fetch_interval
     *
     * @mbggenerated
     */
    public Integer getFetchInterval() {
        return fetchInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.fetch_interval
     *
     * @param fetchInterval the value for cms_webpage_backup.fetch_interval
     *
     * @mbggenerated
     */
    public void setFetchInterval(Integer fetchInterval) {
        this.fetchInterval = fetchInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.retries_since_fetch
     *
     * @return the value of cms_webpage_backup.retries_since_fetch
     *
     * @mbggenerated
     */
    public Integer getRetriesSinceFetch() {
        return retriesSinceFetch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.retries_since_fetch
     *
     * @param retriesSinceFetch the value for cms_webpage_backup.retries_since_fetch
     *
     * @mbggenerated
     */
    public void setRetriesSinceFetch(Integer retriesSinceFetch) {
        this.retriesSinceFetch = retriesSinceFetch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.modified_time
     *
     * @return the value of cms_webpage_backup.modified_time
     *
     * @mbggenerated
     */
    public Long getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.modified_time
     *
     * @param modifiedTime the value for cms_webpage_backup.modified_time
     *
     * @mbggenerated
     */
    public void setModifiedTime(Long modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.prev_modified_time
     *
     * @return the value of cms_webpage_backup.prev_modified_time
     *
     * @mbggenerated
     */
    public Long getPrevModifiedTime() {
        return prevModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.prev_modified_time
     *
     * @param prevModifiedTime the value for cms_webpage_backup.prev_modified_time
     *
     * @mbggenerated
     */
    public void setPrevModifiedTime(Long prevModifiedTime) {
        this.prevModifiedTime = prevModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.content
     *
     * @return the value of cms_webpage_backup.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.content
     *
     * @param content the value for cms_webpage_backup.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.content_type
     *
     * @return the value of cms_webpage_backup.content_type
     *
     * @mbggenerated
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.content_type
     *
     * @param contentType the value for cms_webpage_backup.content_type
     *
     * @mbggenerated
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.title
     *
     * @return the value of cms_webpage_backup.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.title
     *
     * @param title the value for cms_webpage_backup.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.text
     *
     * @return the value of cms_webpage_backup.text
     *
     * @mbggenerated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.text
     *
     * @param text the value for cms_webpage_backup.text
     *
     * @mbggenerated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.score
     *
     * @return the value of cms_webpage_backup.score
     *
     * @mbggenerated
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.score
     *
     * @param score the value for cms_webpage_backup.score
     *
     * @mbggenerated
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.author
     *
     * @return the value of cms_webpage_backup.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.author
     *
     * @param author the value for cms_webpage_backup.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.repr_url
     *
     * @return the value of cms_webpage_backup.repr_url
     *
     * @mbggenerated
     */
    public String getReprUrl() {
        return reprUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.repr_url
     *
     * @param reprUrl the value for cms_webpage_backup.repr_url
     *
     * @mbggenerated
     */
    public void setReprUrl(String reprUrl) {
        this.reprUrl = reprUrl == null ? null : reprUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.batch_id
     *
     * @return the value of cms_webpage_backup.batch_id
     *
     * @mbggenerated
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.batch_id
     *
     * @param batchId the value for cms_webpage_backup.batch_id
     *
     * @mbggenerated
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.segment_id
     *
     * @return the value of cms_webpage_backup.segment_id
     *
     * @mbggenerated
     */
    public String getSegmentId() {
        return segmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.segment_id
     *
     * @param segmentId the value for cms_webpage_backup.segment_id
     *
     * @mbggenerated
     */
    public void setSegmentId(String segmentId) {
        this.segmentId = segmentId == null ? null : segmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.firstFetchTime
     *
     * @return the value of cms_webpage_backup.firstFetchTime
     *
     * @mbggenerated
     */
    public String getFirstfetchtime() {
        return firstfetchtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.firstFetchTime
     *
     * @param firstfetchtime the value for cms_webpage_backup.firstFetchTime
     *
     * @mbggenerated
     */
    public void setFirstfetchtime(String firstfetchtime) {
        this.firstfetchtime = firstfetchtime == null ? null : firstfetchtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.id
     *
     * @return the value of cms_webpage_backup.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.id
     *
     * @param id the value for cms_webpage_backup.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.quote
     *
     * @return the value of cms_webpage_backup.quote
     *
     * @mbggenerated
     */
    public String getQuote() {
        return quote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.quote
     *
     * @param quote the value for cms_webpage_backup.quote
     *
     * @mbggenerated
     */
    public void setQuote(String quote) {
        this.quote = quote == null ? null : quote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.pubDate
     *
     * @return the value of cms_webpage_backup.pubDate
     *
     * @mbggenerated
     */
    public String getPubdate() {
        return pubdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.pubDate
     *
     * @param pubdate the value for cms_webpage_backup.pubDate
     *
     * @mbggenerated
     */
    public void setPubdate(String pubdate) {
        this.pubdate = pubdate == null ? null : pubdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.tag
     *
     * @return the value of cms_webpage_backup.tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.tag
     *
     * @param tag the value for cms_webpage_backup.tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_webpage_backup.catagory
     *
     * @return the value of cms_webpage_backup.catagory
     *
     * @mbggenerated
     */
    public String getCatagory() {
        return catagory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_webpage_backup.catagory
     *
     * @param catagory the value for cms_webpage_backup.catagory
     *
     * @mbggenerated
     */
    public void setCatagory(String catagory) {
        this.catagory = catagory == null ? null : catagory.trim();
    }
}